### ISSUE TITLE
Reconsider opacity prop handling

### ISSUE THREAD

**Issue by muffinresearch** [FirefoxUX/arewedesigntokensyet#23]
@maxxcrawford noted this on slack, and wanted to know what token should be used in place of `1`.

```css
@keyframes fadeIn P
  from { 
    opacity: 0; // This is ignored
  } 
  to { 
    opacity: 1; // This is currently saying it should be a design token.
  } 
}
```

Opacity is included in design tokens as a single token currently `--button-opacity-disabled`.

The props list was originally based on the keys here: `toolkit/themes/shared/design-system/tokens-storybook.mjs` hence the inclusion of opacity.

1. Do we want to reconsider the inclusion of opacity in the tokenizable props list? 
2. Assuming we keep opacity how can the ignores be updated:
  * Can a value of 1 universally be safely ignored or are there other cases where a unit-less value of 1 should be a token?
  * Depending on the answer to 1, we might need to extend the ignores support to ignore certain property/value combinations.
