### ISSUE TITLE
Consider handling of system colors

### ISSUE THREAD

**Issue by muffinresearch** [FirefoxUX/arewedesigntokensyet#27]
How should system colors be handled in this tool?

Currently when exploring #25 to enable adding the themes paths to be tracked but this tool there's a lot of use of system-colors.

For example looking at `/toolkit/themes/linux/global/richlistbox.css` there's css as follows:

```css
richlistbox {
  appearance: auto;
  -moz-default-appearance: listbox;
  margin: 2px 4px;
  background-color: Field;
  color: FieldText;
}
```

Or `/toolkit/themes/windows/mozapps/update/updates.css`

```css
.update-header {
  border-bottom: 2px groove ThreeDFace;
  background-color: Window;
  color: WindowText;
  padding: 0 10px;
}
```

Of these two examples the latter`ThreeDFace`, `Window` and `WindowText` are now deprecated (albeit that's deprecated in the sense of using them in web-pages). 

What I think we need to know for the perspective of the configuration of this tool, is do we see these as being values that we'd expect to be replaced by design tokens in the future, or would they continue to be used in the CSS as they are today?

If the latter, we'd probably want to add them to ignores , and then the next question would we only add the non-deprecated set and look to update the deprecated values to their non-deprecated equivalents? 

References:

- https://developer.mozilla.org/en-US/docs/Web/CSS/system-color
- https://drafts.csswg.org/css-color/#css-system-colors
- https://drafts.csswg.org/css-color/#deprecated-system-colors

Sidenote but relevant to how these are ignored if we go that route: ['these keywords are case insensitive' ](https://developer.mozilla.org/en-US/docs/Web/CSS/system-color#syntax)

/cc @jsimplicio for input.
