### ISSUE TITLE
Correct var resolution for vars defined in the same selector

### ISSUE THREAD

**Issue by muffinresearch** [FirefoxUX/arewedesigntokensyet#30]
Currently with CSS like: 

```css
  ::slotted(:first-child) {
    --visual-picker-item-child-border-radius: calc(var(--visual-picker-item-border-radius) - var(--visual-picker-item-border-width));
    border-radius: var(--visual-picker-item-child-border-radius);
  }
```

A var is not resolved it if it is defined in the same selector. This should be resolved and the use of design tokens should be detected correctly.
