### ISSUE TITLE
Provide better handling for when a var is redefined for different use-cases.

### ISSUE THREAD

**Issue by muffinresearch** [FirefoxUX/arewedesigntokensyet#8]
https://firefoxux.github.io/arewedesigntokensyet/browser/components/contextualidentity/content/usercontext.css/ has an example of a falsely identified ignore. 

In this case the vars `--identity-icon-color` are defined multiple types under different classes. The last one happens to be `currentColor` so this is marked as an ignore.

What should happen in this case is it should only be marked as a pass if all values reflect design tokens or ignore values.

Here's a sample, in this case `color: var(--identity-tab-color);` is marked as an ignore but should be a fail. 

```css
.identity-color-pink {
  --identity-tab-color: #ff4bda;
  --identity-icon-color: #ff4bda;
}

.identity-color-purple {
  --identity-tab-color: #af51f5;
  --identity-icon-color: #af51f5;
}

.identity-color-toolbar {
  --identity-tab-color: currentColor;
  --identity-icon-color: currentColor;
}

#userContext-label {
  color: var(--identity-tab-color);
  margin: 0;
  max-width: 8em;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
